Allow private connection for Github self-hosted runner
oracle-actions/configure-kubectl-oke pull request #17
Opened 2022-11-09 17:58 UTC by tonybolzan

Private connections in k8s Cluster is a desired security tip. And running a self-hosted runner in a private VCN can accomplish the connections without a public IP.

With this modification public and private connections are allowed without braking compatibility.

2022-11-09 19:33 UTC, Djelibeybi commented
Thanks! Have you signed the Oracle Contributor Agreement? If not, please visit https://oca.opensource.oracle.com to sign it.

2022-11-09 19:40 UTC, Djelibeybi commented
This probably needs some error checking/catching or restrictions to only be available for runners with a specific tag.

2022-11-09 21:00 UTC, tonybolzan commented
Can be a specific configuration on `with:` ? like `allowPrivateAccess` or other better name.
What you think ?
```yml
    steps:
      - uses: oracle-actions/configure-kubectl-oke@v1
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}
          allowPrivateAccess: true
```

2022-11-09 21:33 UTC, Djelibeybi commented
That seems reasonable to me.

2022-11-10 14:03 UTC, tonybolzan commented
> Thanks! Have you signed the Oracle Contributor Agreement? If not, please visit https://oca.opensource.oracle.com to sign it. Adding another commit to the PR will also trigger the Bot to verify that it's been signed.

The OCA has bean rejected, I submited another trial with a updated information.
But this project is not in the OCA project list, so I had to select `other` in the project list.
And I received this message `Other: For "Other" project(s), reach out to the project owner(s) to add the project(s) to the system.` on [this](https://oca.opensource.oracle.com/?ojr=contrib-create%3Btype%3Dindividual) form

2022-11-12 03:59 UTC, Djelibeybi commented
I have added the project to the OCA application, so you should be able to submit now. Sorry for the hurdles, but you're the first person to submit a PR to any of our actions. :)

2022-11-14 13:48 UTC, tonybolzan commented
I'm waiting for the OCA to be approved to update the PR.

2022-11-16 21:00 UTC, tonybolzan commented
PR Updated, you can review.

2022-11-16 21:03 UTC, Djelibeybi requested changes

2022-11-16 21:03 UTC, Djelibeybi commented on README.md
> +The target OKE cluster must have a **public Kubernetes API Endpoint** or you must run on a [Self-Hosted GitHub Action][6] to enable Private Endpoint with Inputs in order for the GitHub Action to succ
```suggestion
The target OKE cluster must have a **public Kubernetes API Endpoint** or you must deploy a [self-hosted GitHub Runner][6] to an instance on the same private subnet to enable Private Endpoint with Inputs in order for the GitHub Action to successfully connect to the cluster.
```

2022-11-16 21:03 UTC, Djelibeybi commented on README.md
> +* `enablePrivateEndpoint`: (Optional) If you want to connect on a Private Kubernetes API Endpoint. Default: false
```suggestion
* `enablePrivateEndpoint`: (Optional) set this to 'true' if you need to connect to a private Kubernetes API endpoint. Requires a self-hosted GitHub Runner deployed to an instance on the same private subnet. Default: false
```

2022-11-17 20:49 UTC, Djelibeybi approved these changes

2022-11-17 21:03 UTC, closed without merging

2022-11-17 21:04 UTC, Djelibeybi commented
I merged this manually, so closing the PR.